// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"MOG_HPGauge","status":true,"description":"(v1.3) Apresenta um medidor de HP do alvo.","parameters":{"Gauge For Actors":"true","Gauge For Enemies":"true","Show HP On Selection":"true","Fade Duration":"90","Slide Animation":"true","Show HP Number Actor":"false","Show HP Number Enemy":"true","Required to Kill":"false","Actor Layout X-Axis":"0","Actor Layout Y-Axis":"0","Actor Meter X-Axis":"0","Actor Meter Y-Axis":"3","Actor HP Number X-Axis":"-25","Actor HP Number Y-Axis":"-22","Enemy Layout X-Axis":"0","Enemy Layout Y-Axis":"0","Enemy Meter X-Axis":"8","Enemy Meter Y-Axis":"10","Enemy HP Number X-Axis":"-25","Enemy HP Number Y-Axis":"-19"}}
];
